extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - prettier
  - react
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  react/jsx-uses-react: off
  quotes:
    - 2
    - single
  import/extensions: off
env:
  browser: true
  jest/globals: true
  node: true
  commonjs: true
  webextensions: true
settings:
  react:
    pragma: React
    version: detect
